package com.example.ladycure.data

open class User(
    open val id : String,  // will be generated by firebase
   open val email: String,
    open val name: String,
    open val surname: String,
  open  val dateOfBirth: String,
  open  val role : Role,
  open  val profilePictureUrl: String,
)

enum class Role(val value: String) {
    DOCTOR("Doctor"),
    PATIENT("Patient"),
    ADMIN("Admin");

    companion object {
        fun fromValue(value: String): Role {
            return values().firstOrNull { it.value == value } ?: PATIENT
        }
    }
}




